# Deployment of the secure, tested app on the remote server

name: Deploy to Server

on:
    workflow_call:

jobs:
    deploy:
        runs-on: ubuntu-latest

        env:
            DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
            DOCKER_TAG: ${{ github.sha }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: SSH to Production Server & Create app folder
              uses: appleboy/ssh-action@v1.2.5
              with:
                host: ${{ secrets.EC2_SSH_HOST }}
                username: ${{ secrets.EC2_SSH_USER }}
                key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
                script: |
                    echo "Installing required packages & Creating directories"
                    sudo apt-get update && sudo apt install docker.io docker-compose-v2 -y
                    sudo usermod -aG docker $USER && newgrp docker
                    mkdir -p ai-chat-app-prod
            
            - name: Copy docker-compose.yml to remote server
              uses: appleboy/scp-action@v1
              with:
                host: ${{ secrets.EC2_SSH_HOST }}
                username: ${{ secrets.EC2_SSH_USER }}
                key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
                source: "docker-compose.yml"
                target: "/home/ubuntu/ai-chat-app-prod"
                    
            - name: SSH to Production Server & Run the app
              uses: appleboy/ssh-action@v1.2.5
              with:
                host: ${{ secrets.EC2_SSH_HOST }}
                username: ${{ secrets.EC2_SSH_USER }}
                key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
                script: |
                    export DOCKERHUB_USER=${{ vars.DOCKERHUB_USER }}
                    export DOCKER_TAG=${{ github.sha }}
                    echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ vars.DOCKERHUB_USER }} --password-stdin
                    cd ~/ai-chat-app-prod
                    touch .env
                    chmod 800 .env
                    echo "GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}" >> .env
                    docker compose down && docker compose up -d --build --force-recreate --pull always
                    