name: DevSecOps End to End Pipeline

on:
    # workflow_dispatch:
    push:
        branches: [main]

jobs:

    # CI (Continuous Integration with Security Scanning)

    # 1. Code Quality

    code-quality:
        uses: ./.github/workflows/code-quality.yml

    # 2. Dependency & Security Scans

    dependency-check:
        needs: [code-quality]
        uses: ./.github/workflows/dependency-check.yml

    secrets-scan:
        needs: [code-quality]
        uses: ./.github/workflows/secrets-scan.yml

    scan-dockerfile:
        needs: [code-quality]
        uses: ./.github/workflows/scan-dockerfile.yml

    # 3. Unit & Integration Testing 

    tests:
        needs: [dependency-check, secrets-scan, scan-dockerfile]
        uses: ./.github/workflows/tests.yml

    # 4. Build & Image Scan
    build:
        needs: [tests]
        uses: ./.github/workflows/docker-build-push.yml
        secrets: inherit

    # 5. Image Scan
    trivy:
        needs: [build]
        uses: ./.github/workflows/image-scan.yml
        secrets: inherit

    # 6. Deploy to Production (Only triggered if Image Scan is successful)
    deploy:
        needs: [trivy]
        uses: ./.github/workflows/deploy-to-server.yml
        secrets: inherit

    #7. Slack-Notification
    Notification:
        needs: [code-quality, dependency-check, secrets-scan, scan-dockerfile, tests, build, trivy, deploy]
        if: always()
        uses: ./.github/workflows/Slack-Notify.yml
        with:
          status: ${{ contains(needs.*.result, 'failure') && 'failure' || 'success' }}
        secrets:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    
