# Scans - API Keys, Sensitive data, credentials
# Using -  GitLeaks (Checks git commit history)

name: Secrets Scan

on:
    workflow_call:

jobs:
    secret-scan:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout code
              uses: actions/checkout@v6
              with:
                fetch-depth: 0

            - name: Run GitLeaks Scanner
              uses: gitleaks/gitleaks-action@v3
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Managed by github actions itself
